### ISSUE TITLE
How can you deploy this?

### ISSUE THREAD

**Issue by DrSayre** [mitchlloyd/ember-rails-authentication-example#2]
Without the proxy flag, the rails server doesn't have access to the session.  What is the best way to deploy this solution?

**Comment by mitchlloyd** [comment]
The Rails server here is just using its default cookie session, so the concern is that the two apps need to be on the same domain? (Let me know if I'm misunderstanding).

Here are a few approaches to deployment I've seen in action:

1) Run `ember build --environment production --output-path ../public` in a build script (for instance on heroku with a custom buildpack) to put the assets into the Rails public directory. This is kind of clunky but an okay way to get started.

2) Setup Nginx in your environment to revery proxy calls to /api to your Rails app. Tried and true.

3) Use [ember-cli-deploy](http://ember-cli.github.io/ember-cli-deploy/). The high-level approach here is to upload your assets anywhere, and then serve them from an index file that your backend controls.

**Comment by DrSayre** [comment]
Thanks!  I was over thinking it and making it more complicated.

**Comment by mitchlloyd** [comment]
Glad I could help!
